coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 1%
    patch:
      default:
        target: 90%

comment:
  layout: "header, diff, files"
  require_changes: true

ignore:
  - "crates/devboy-cli/src/main.rs"
